### ISSUE TITLE
Switch must be exhaustive error

### ISSUE THREAD

**Issue by ryantallmadge** [aj-bartocci/innernet#1]
Getting a `Switch must be exhaustive` error in `URLProtocolInterceptor -> handleIntercept -> switch response` 

Xcode 14
Version 0.0.2

Looks like switch code block might need another case added?

```                
case .redirected(data: let data, response: let response, error: let error):
```

**Comment by aj-bartocci** [comment]
fixed with https://github.com/aj-bartocci/innernet/pull/2
